export const LOAD_WORKFLOWS_SUCCESS = "tse/workflows/LOAD_WORKFLOWS_SUCCESS";
export const CREATE_WORKFLOW_SUCCESS = "tse/workflows/CREATE_WORKFLOW_SUCCESS";
export const UPDATE_WORKFLOW_SUCCESS = "tse/workflows/UPDATE_WORKFLOW_SUCCESS";
