export const LOAD_WORKFLOW_ACTIONS_SUCCESS =
  "tse/actions/LOAD_WORKFLOW_ACTIONS_SUCCESS";
export const CREATE_WORKFLOW_TEMP_ACTION =
  "tse/actions/CREATE_WORKFLOW_TEMP_ACTION";
export const UPDATE_WORKFLOW_TEMP_ACTION =
  "tse/actions/UPDATE_WORKFLOW_TEMP_ACTION";
export const REPLACE_WORKFLOW_TEMP_ACTION_SUCCESS =
  "tse/actions/REPLACE_WORKFLOW_TEMP_ACTION_SUCCESS";
export const REMOVE_WORKFLOW_TEMP_ACTION =
  "tse/actions/REMOVE_WORKFLOW_TEMP_ACTION";
export const REMOVE_WORKFLOW_ACTION = "tse/actions/REMOVE_WORKFLOW_ACTION";
