export const CLEANUP_NOTIFICATIONS = "tse/ActivateForm/CLEANUP_NOTIFICATIONS";
export const SET_DIALOG_VISIBLE = "tse/ActivateForm/SET_DIALOG_VISIBLE";
export const ACTIVATE_WORKFLOW_PENDING =
  "tse/ActivateForm/ACTIVATE_WORKFLOW_PENDING";
export const ACTIVATE_WORKFLOW_SUCCESS =
  "tse/ActivateForm/ACTIVATE_WORKFLOW_SUCCESS";
export const ACTIVATE_WORKFLOW_ERROR =
  "tse/ActivateForm/ACTIVATE_WORKFLOW_ERROR";
